新接口 CqNoticeEssencePostContext.GroupId和一些其他的东西
OrgEleCho/EleCho.GoCqHttpSdk pull request #52
Opened 2024-03-29 03:57 UTC by gdr2333

新的接口：
EleCho.GoCqHttpSdk.Post.Interface.IGroupPostContext：所有群聊上报消息（除了戳一戳）都实现了该接口，可以读取群号
EleCho.GoCqHttpSdk.ICqActionAndPostSession：正向和反向websocket会话实现了这个接口，其实就是ICqPostSession和ICqActionSession
成员变更：CqNoticeEssencePostContext现在实现了GroupId
行为变更：几乎所有上报消息的成员的set访问器都改为了internel set，因为你根本就不应该更改这些内容
其他：
将.net 8.0添加到目标框架
csproj文件的一些清理

2024-03-29 04:05 UTC, gdr2333 commented
啊，忘写了：
CqPrivateMessagePostContext和CqGroupMessagePostContext的Sender属性已转移到基类CqMessagePostContext

2024-03-30 05:01 UTC, SlimeNull commented on src/EleCho.GoCqHttpSdk/CqRWsSession.cs
这个抽象没必要

2024-03-30 05:11 UTC, SlimeNull requested changes
1. 删去 IActionAndPostSession
2. CqMessagePostContext 的 Sender 应该在当前类型的 ReadModel 中初始化

2024-03-30 05:11 UTC, SlimeNull commented on src/EleCho.GoCqHttpSdk/ICqActionAndPostSession.cs
我建议删掉这个抽象

2024-03-30 05:11 UTC, SlimeNull commented on src/EleCho.GoCqHttpSdk/Post/Base/CqMessagePostContext.cs
请在 ReadModel 中初始化这个字段... 既然成员在这就应该初始化

2024-03-30 05:13 UTC, SlimeNull commented
另外, 既然已经有了 IGroupPostContext 接口抽象, 那么这个接口最好尽可能包含它应该有的东西, 然后最好添加一切其他的, 同等级的接口抽象, 例如私聊上报 IPrivatePostContext 这样的

2024-03-31 10:05 UTC, SlimeNull approved these changes

2024-03-31 10:05 UTC, SlimeNull approved these changes

2024-03-31 10:09 UTC, merged